"""Execution orchestration for unified_search.

Design:
    This module runs the plan generated by unified_planning.py. It coordinates
    source execution, deep-search expansion, enrichment, aggregation, and
    session updates while keeping the outer tool handler thin.

Maintenance:
    Add runtime orchestration here, not in planning or formatting modules.
    Preserve the clear handoff from UnifiedSearchPlan to execution result so
    retries and source metrics remain testable.
"""

from __future__ import annotations

import asyncio
import contextlib
import logging
from collections.abc import Awaitable, Callable, Mapping
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

from pubmed_search.application.search.result_aggregator import ResultAggregator
from pubmed_search.application.timeline import TimelineBuilder, build_research_tree
from pubmed_search.domain.entities.article import UnifiedArticle
from pubmed_search.infrastructure.sources.preprints import PreprintSearcher
from pubmed_search.infrastructure.sources.registry import get_source_registry
from pubmed_search.presentation.mcp_server.session_tools import notify_session_resources_updated
from pubmed_search.shared.source_contracts import (
    SourceAdapterCall,
    SourceAdapterResult,
    format_source_adapter_error,
    gather_source_adapter_calls,
)

from .agent_output import is_structured_output_format
from .tool_session import _record_search_only
from .unified_enrichment import (
    _enrich_with_crossref,
    _enrich_with_journal_metrics,
    _enrich_with_similarity_scores,
    _enrich_with_unpaywall,
    _is_preprint,
)
from .unified_helpers import DispatchStrategy, RelaxationResult, SearchDepthMetrics
from .unified_source_search import (
    _auto_relax_search,
    _execute_deep_search,
    _search_pubmed,
)

if TYPE_CHECKING:
    from mcp.server.fastmcp import Context

    from pubmed_search.application.search.ranking_algorithms import SourceDisagreement
    from pubmed_search.infrastructure.ncbi import LiteratureSearcher

    from .unified_planning import ProgressReporter, UnifiedSearchPlan

logger = logging.getLogger(__name__)
SOURCE_SEARCH_TIMEOUT_SECONDS = 25.0

SearchRunner = Callable[
    [str, int, int | None, int | None, dict[str, Any]], Awaitable[tuple[list[UnifiedArticle], int | None]]
]


@dataclass
class UnifiedSearchExecutionResult:
    ranked: list[UnifiedArticle]
    stats: Any
    pubmed_total_count: int | None
    source_api_counts: dict[str, tuple[int, int | None]]
    preprint_results: dict[str, Any]
    deep_search_metrics: SearchDepthMetrics | None
    relaxation_result: RelaxationResult | None
    source_disagreement: SourceDisagreement | None
    reproducibility_score: Any
    research_context_preview: str | None
    research_context_data: dict[str, Any] | None
    prefetched_trials: list[Any] | None


async def _search_single_source(
    source: str,
    plan: UnifiedSearchPlan,
    search_functions: Mapping[str, SearchRunner],
) -> SourceAdapterResult[UnifiedArticle]:
    query = plan.query
    limit = plan.request.limit
    min_year = plan.effective_min_year
    max_year = plan.effective_max_year
    advanced_filters = plan.request.advanced_filters

    if source == "crossref":
        return SourceAdapterResult.empty(source="crossref", operation="search")

    runner = search_functions.get(source)
    if runner is None:
        return SourceAdapterResult.empty(source=source, operation="search")

    articles, total_count = await runner(query, limit, min_year, max_year, advanced_filters)
    return SourceAdapterResult(
        source=source,
        operation="search",
        items=articles,
        total_count=total_count or len(articles),
        metadata={"total_available": total_count},
    )


async def execute_unified_search(
    plan: UnifiedSearchPlan,
    searcher: LiteratureSearcher,
    *,
    progress: ProgressReporter,
    ctx: Context | None = None,
    search_functions: Mapping[str, SearchRunner],
    timeline_builder_cls: type[TimelineBuilder] = TimelineBuilder,
    research_tree_builder: Callable[[Any], Any] = build_research_tree,
) -> UnifiedSearchExecutionResult:
    """Execute a planned unified search and return normalized output state."""
    request = plan.request
    analysis = plan.analysis
    registry = get_source_registry()

    all_results: list[list[UnifiedArticle]] = []
    pubmed_total_count: int | None = None
    source_api_counts: dict[str, tuple[int, int | None]] = {}
    preprint_results: dict[str, Any] = {}
    deep_search_metrics: SearchDepthMetrics | None = None
    relaxation_result: RelaxationResult | None = None

    clinical_trials_task: asyncio.Task | None = None
    if not is_structured_output_format(request.output_format):
        try:
            from pubmed_search.infrastructure.sources.clinical_trials import search_related_trials

            trial_query = " ".join(plan.query.split()[:5])
            clinical_trials_task = asyncio.create_task(search_related_trials(trial_query, limit=3))
            parent_task = asyncio.current_task()
            if parent_task is not None:
                def _cancel_orphaned_trials(_completed_parent: asyncio.Task[Any]) -> None:
                    if clinical_trials_task is not None and not clinical_trials_task.done():
                        clinical_trials_task.cancel()

                parent_task.add_done_callback(_cancel_orphaned_trials)
        except Exception:
            logger.debug("Clinical trials module not available, skipping")

    if request.deep_search and plan.enhanced_query and plan.enhanced_query.strategies:
        enhanced_query = plan.enhanced_query
        if plan.user_sources:
            original_count = len(enhanced_query.strategies)
            enhanced_query.strategies = [
                strategy for strategy in enhanced_query.strategies if strategy.source in plan.user_sources
            ]
            if not enhanced_query.strategies:
                from pubmed_search.application.search.semantic_enhancer import SearchPlan

                for source in plan.user_sources:
                    definition = registry.get(source)
                    if definition and definition.supports_primary_search and source != "crossref":
                        enhanced_query.strategies.append(
                            SearchPlan(
                                name=f"user_specified_{source}",
                                query=enhanced_query.original_query,
                                source=source,
                                priority=1,
                                expected_precision=0.5,
                                expected_recall=0.5,
                            )
                        )
            filtered_count = original_count - len(enhanced_query.strategies)
            if filtered_count > 0:
                logger.info("Filtered %s strategies to match user sources: %s", filtered_count, plan.user_sources)

        await progress(4, 10, f"Deep search: {len(enhanced_query.strategies)} strategies...")
        logger.info("Executing DEEP SEARCH with %s strategies", len(enhanced_query.strategies))
        all_results, deep_search_metrics, pubmed_total_count, source_api_counts = await _execute_deep_search(
            searcher,
            enhanced_query,
            request.limit,
            plan.effective_min_year,
            plan.effective_max_year,
            request.advanced_filters,
        )
        logger.info(
            "Deep search: %s strategies, %s with results, depth score: %.0f",
            deep_search_metrics.strategies_executed,
            deep_search_metrics.strategies_with_results,
            deep_search_metrics.depth_score,
        )
    else:
        logger.info("Using traditional source-based search (no deep search)")
        search_sources = [source for source in plan.dispatch_sources if source != "crossref"]

        def _build_search_call(source: str) -> SourceAdapterCall[UnifiedArticle]:
            async def _execute() -> SourceAdapterResult[UnifiedArticle]:
                return await _search_single_source(source, plan, search_functions)

            return SourceAdapterCall(source=source, operation="search", execute=_execute)

        search_results = await gather_source_adapter_calls(
            [_build_search_call(source) for source in search_sources],
            per_call_timeout=SOURCE_SEARCH_TIMEOUT_SECONDS,
        )
        for result in search_results:
            for error in result.errors:
                logger.error("Search failed: %s", format_source_adapter_error(error))

            articles = result.items
            raw_total_count = result.metadata.get("total_available")
            total_count = raw_total_count if isinstance(raw_total_count, int) else None
            if articles:
                all_results.append(articles)
            source_api_counts[result.source] = (len(articles), total_count)
            if result.source == "pubmed" and total_count is not None:
                pubmed_total_count = total_count
            logger.info(
                "%s: %s results%s", result.source, len(articles), f" (total: {total_count})" if total_count else ""
            )

    if request.include_preprints:
        try:
            preprint_searcher = PreprintSearcher()
            preprint_query = (
                plan.query.split("[MeSH]")[0].replace('"', "").strip() if "[MeSH]" in plan.query else plan.query
            )
            preprint_results = await preprint_searcher.search_medical_preprints(
                query=preprint_query, limit=min(request.limit, 10)
            )
            logger.info("Preprints: %s results", preprint_results.get("total", 0))
        except Exception as exc:
            logger.warning("Preprint search failed: %s", exc)
            preprint_results = {}

    await progress(5, 10, "Aggregating results...")
    aggregator = ResultAggregator(plan.ranking_config)
    articles, stats = aggregator.aggregate(all_results)
    logger.info("Aggregation: %s unique from %s total", stats.unique_articles, stats.total_input)

    if request.auto_relax and stats.unique_articles == 0 and not analysis.identifiers:
        logger.info("0 results — attempting auto-relaxation")
        relaxation_result = await _auto_relax_search(
            searcher,
            plan.query,
            request.limit,
            request.min_year or analysis.year_from,
            request.max_year or analysis.year_to,
            request.advanced_filters,
        )
        if relaxation_result and relaxation_result.successful_step:
            step = relaxation_result.successful_step
            relaxed_articles, _ = await _search_pubmed(
                searcher,
                step.query,
                request.limit,
                step.min_year,
                step.max_year,
                **step.advanced_filters,
            )
            all_results = [relaxed_articles]
            articles, stats = aggregator.aggregate(all_results)
            pubmed_total_count = relaxation_result.total_results
            logger.info("Auto-relaxation: %s results at level %s (%s)", stats.unique_articles, step.level, step.action)

    await progress(6, 10, "Enriching results...")
    enrichment_tasks: list[asyncio.Task] = []  # type: ignore[type-arg]
    if "crossref" in plan.dispatch_sources:
        enrichment_tasks.append(asyncio.create_task(_enrich_with_crossref(articles)))
    if "openalex" in plan.dispatch_sources:
        enrichment_tasks.append(asyncio.create_task(_enrich_with_journal_metrics(articles)))
    if request.include_oa_links and DispatchStrategy.should_enrich_with_unpaywall(analysis):
        enrichment_tasks.append(asyncio.create_task(_enrich_with_unpaywall(articles)))
    if enrichment_tasks:
        await asyncio.gather(*enrichment_tasks, return_exceptions=True)

    if request.peer_reviewed_only and articles:
        from pubmed_search.domain.entities.article import ArticleType

        pre_filter_count = len(articles)
        articles = [article for article in articles if not _is_preprint(article, ArticleType)]
        filtered_count = pre_filter_count - len(articles)
        if filtered_count > 0:
            logger.info("Peer-review filter: removed %s non-peer-reviewed articles", filtered_count)

    await progress(8, 10, "Ranking results...")
    ranked = aggregator.rank(articles, plan.ranking_config, plan.query)
    if request.limit and len(ranked) > request.limit:
        ranked = ranked[: request.limit]

    if request.include_similarity_scores:
        _enrich_with_similarity_scores(ranked, plan.query)

    source_disagreement = None
    if len(source_api_counts) > 1:
        from pubmed_search.application.search.ranking_algorithms import analyze_source_disagreement

        source_disagreement = analyze_source_disagreement(ranked)

    from pubmed_search.application.search.reproducibility import calculate_reproducibility

    sources_queried_list = (
        list(source_api_counts.keys())
        if source_api_counts
        else [source for source in plan.dispatch_sources if source != "crossref"]
    )
    sources_responded_list = (
        [source for source in sources_queried_list if source_api_counts.get(source, (0, None))[0] > 0]
        if source_api_counts
        else sources_queried_list
    )
    reproducibility = calculate_reproducibility(
        query=plan.query,
        sources_queried=sources_queried_list,
        sources_responded=sources_responded_list,
        articles=ranked,
        has_source_counts=bool(source_api_counts),
    )

    research_context_preview: str | None = None
    research_context_data: dict[str, Any] | None = None
    if request.include_research_context and ranked:
        pmids_for_context = [str(article.pmid) for article in ranked if getattr(article, "pmid", None)][:20]
        if pmids_for_context:
            try:
                context_builder = timeline_builder_cls(searcher)
                context_timeline = await context_builder.build_timeline_from_pmids(
                    pmids=pmids_for_context, topic=analysis.original_query
                )
                if context_timeline.events:
                    context_tree = research_tree_builder(context_timeline)
                    research_context_preview = context_tree.to_text_tree()
                    research_context_data = context_tree.to_dict()
            except Exception as exc:
                logger.debug("Research context graph skipped: %s", exc)

    _record_search_only(ranked, analysis.original_query)
    await notify_session_resources_updated(ctx)

    prefetched_trials: list[Any] | None = None
    if clinical_trials_task:
        if clinical_trials_task.done():
            try:
                prefetched_trials = clinical_trials_task.result()
            except Exception:
                prefetched_trials = None
        else:
            clinical_trials_task.cancel()
            with contextlib.suppress(asyncio.CancelledError):
                await clinical_trials_task

    return UnifiedSearchExecutionResult(
        ranked=ranked,
        stats=stats,
        pubmed_total_count=pubmed_total_count,
        source_api_counts=source_api_counts,
        preprint_results=preprint_results,
        deep_search_metrics=deep_search_metrics,
        relaxation_result=relaxation_result,
        source_disagreement=source_disagreement,
        reproducibility_score=reproducibility,
        research_context_preview=research_context_preview,
        research_context_data=research_context_data,
        prefetched_trials=prefetched_trials,
    )


__all__ = ["UnifiedSearchExecutionResult", "execute_unified_search"]
