"""Execution orchestration for unified_search.

Design:
    This module runs the plan generated by unified_planning.py. It coordinates
    source execution, deep-search expansion, enrichment, aggregation, and
    session updates while keeping the outer tool handler thin.

Maintenance:
    Add runtime orchestration here, not in planning or formatting modules.
    Preserve the clear handoff from UnifiedSearchPlan to execution result so
    retries and source metrics remain testable.
"""

from __future__ import annotations

import asyncio
import logging
from collections.abc import Awaitable, Callable, Mapping
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

from pubmed_search.application.search.result_aggregator import ResultAggregator
from pubmed_search.application.timeline import TimelineBuilder, build_research_tree
from pubmed_search.domain.entities.article import UnifiedArticle
from pubmed_search.shared.source_contracts import (
    SourceAdapterCall,
    SourceAdapterResult,
    format_source_adapter_error,
    gather_source_adapter_calls,
)

from .agent_output import is_structured_output_format
from .unified_enrichment import (
    _enrich_with_crossref,
    _enrich_with_journal_metrics,
    _enrich_with_similarity_scores,
    _enrich_with_unpaywall,
    _is_preprint,
)
from .unified_helpers import DispatchStrategy, RelaxationResult, SearchDepthMetrics
from .unified_source_search import (
    _auto_relax_search,
    _execute_deep_search,
)

if TYPE_CHECKING:
    from mcp.server.mcpserver import Context

    from pubmed_search.application.search.ranking_algorithms import SourceDisagreement
    from pubmed_search.infrastructure.ncbi import LiteratureSearcher

    from .unified_planning import ProgressReporter, UnifiedSearchPlan

logger = logging.getLogger(__name__)
SOURCE_SEARCH_TIMEOUT_SECONDS = 25.0
CLINICAL_TRIALS_PREFETCH_TIMEOUT_SECONDS = 0.5
_PREPRINT_SOURCE_KEYS = frozenset({"arxiv", "medrxiv", "biorxiv"})

SearchRunnerOutcome = tuple[list[UnifiedArticle], int | None] | SourceAdapterResult[UnifiedArticle]
SearchRunner = Callable[[str, int, int | None, int | None, dict[str, Any]], Awaitable[SearchRunnerOutcome]]


@dataclass
class UnifiedSearchExecutionResult:
    ranked: list[UnifiedArticle]
    stats: Any
    pubmed_total_count: int | None
    source_api_counts: dict[str, tuple[int, int | None]]
    deep_search_metrics: SearchDepthMetrics | None
    relaxation_result: RelaxationResult | None
    source_disagreement: SourceDisagreement | None
    reproducibility_score: Any
    research_context_preview: str | None
    research_context_data: dict[str, Any] | None
    prefetched_trials: list[Any] | None
    clinical_trials_query: str | None
    clinical_trials_status: str
    source_errors: list[dict[str, Any]]
    source_statuses: dict[str, str]
    source_metadata: dict[str, dict[str, Any]]


def _source_error_payload(error: Any) -> dict[str, Any]:
    """Serialize one source adapter error for agent-facing diagnostics."""
    status_code = getattr(error, "status_code", None)
    source = str(getattr(error, "source", "unknown"))
    payload: dict[str, Any] = {
        "source": source,
        "operation": str(getattr(error, "operation", "search")),
        "message": str(getattr(error, "message", "")),
        "kind": str(getattr(error, "kind", "unexpected")),
        "retryable": bool(getattr(error, "retryable", False)),
    }
    if status_code is not None:
        payload["status_code"] = status_code
    if status_code == 429:
        payload["status"] = "rate_limited"
        payload["suggestion"] = (
            'Set S2_API_KEY/SEMANTIC_SCHOLAR_API_KEY, retry later, or use sources="auto,-semantic_scholar".'
            if source == "semantic_scholar"
            else f"Respect {source} retry/reset guidance, reduce request frequency, or retry after the shared cooldown."
        )
    else:
        payload["status"] = "error"
    return payload


def _allows_preprint_articles(*, include_preprints: bool, dispatch_sources: list[str]) -> bool:
    """Return whether preprints are an explicit part of this unified search."""
    return include_preprints or any(source in _PREPRINT_SOURCE_KEYS for source in dispatch_sources)


async def _search_single_source(
    source: str,
    plan: UnifiedSearchPlan,
    search_functions: Mapping[str, SearchRunner],
    *,
    limit_override: int | None = None,
) -> SourceAdapterResult[UnifiedArticle]:
    query = plan.query if source == "pubmed" else plan.provider_neutral_query
    limit = plan.request.limit if limit_override is None else limit_override
    min_year = plan.effective_min_year
    max_year = plan.effective_max_year
    runner_options: dict[str, Any] = dict(plan.request.advanced_filters)
    if source in {"openalex", "semantic_scholar"}:
        runner_options["_retrieval_mode"] = plan.request.retrieval_mode

    if source == "crossref":
        msg = "Crossref is an enrichment source and cannot be used as the only primary search adapter"
        raise ValueError(msg)

    runner = search_functions.get(source)
    if runner is None:
        msg = f"No search adapter is registered for source '{source}'"
        raise ValueError(msg)

    outcome = await runner(query, limit, min_year, max_year, runner_options)
    if isinstance(outcome, SourceAdapterResult):
        outcome.metadata.setdefault("requested_mode", plan.request.retrieval_mode)
        if source != "pubmed" and plan.request.advanced_filters:
            warnings = outcome.metadata.setdefault("warnings", [])
            warning = (
                f"{source} does not apply PubMed-only filter(s): {', '.join(sorted(plan.request.advanced_filters))}"
            )
            if isinstance(warnings, list) and warning not in warnings:
                warnings.append(warning)
        return outcome

    articles, total_count = outcome
    filter_warnings: list[str] = []
    if source != "pubmed" and plan.request.advanced_filters:
        filter_warnings.append(
            f"{source} does not apply PubMed-only filter(s): {', '.join(sorted(plan.request.advanced_filters))}"
        )
    return SourceAdapterResult(
        source=source,
        operation="search",
        items=articles,
        total_count=total_count or len(articles),
        status="ok" if articles else "empty",
        metadata={
            "total_available": total_count,
            "requested_mode": plan.request.retrieval_mode,
            "provider_mode": "default",
            "warnings": filter_warnings,
        },
    )


async def execute_unified_search(
    plan: UnifiedSearchPlan,
    searcher: LiteratureSearcher,
    *,
    progress: ProgressReporter,
    ctx: Context | None = None,
    search_functions: Mapping[str, SearchRunner],
    timeline_builder_cls: type[TimelineBuilder] = TimelineBuilder,
    research_tree_builder: Callable[[Any], Any] = build_research_tree,
) -> UnifiedSearchExecutionResult:
    """Execute a planned unified search and return normalized output state."""
    request = plan.request
    analysis = plan.analysis
    all_results: list[list[UnifiedArticle]] = []
    pubmed_total_count: int | None = None
    source_api_counts: dict[str, tuple[int, int | None]] = {}
    deep_search_metrics: SearchDepthMetrics | None = None
    relaxation_result: RelaxationResult | None = None
    source_errors: list[dict[str, Any]] = []
    source_statuses: dict[str, str] = {}
    source_metadata: dict[str, dict[str, Any]] = {}

    clinical_trials_task: asyncio.Task | None = None
    clinical_trials_query: str | None = None
    clinical_trials_status = "not_requested"
    if request.include_clinical_trials and is_structured_output_format(request.output_format):
        clinical_trials_status = "not_run_structured_output"
    if request.include_clinical_trials and not is_structured_output_format(request.output_format):
        clinical_trials_status = "starting"
        try:
            from pubmed_search.infrastructure.sources.clinical_trials import search_related_trials

            clinical_trials_query = " ".join(plan.provider_neutral_query.split()[:5])
            clinical_trials_task = asyncio.create_task(search_related_trials(clinical_trials_query, limit=3))
            clinical_trials_status = "pending"
            parent_task = asyncio.current_task()
            if parent_task is not None:

                def _cancel_orphaned_trials(_completed_parent: asyncio.Task[Any]) -> None:
                    if clinical_trials_task is not None and not clinical_trials_task.done():
                        clinical_trials_task.cancel()

                parent_task.add_done_callback(_cancel_orphaned_trials)
        except Exception:
            clinical_trials_status = "unavailable"
            logger.debug("Clinical trials module not available, skipping")

    if request.deep_search and plan.enhanced_query and plan.deep_strategies:
        enhanced_query = plan.enhanced_query
        await progress(4, 10, f"Deep search: {len(plan.deep_strategies)} strategies...")
        logger.info("Executing DEEP SEARCH with %s strategies", len(plan.deep_strategies))
        (
            all_results,
            deep_search_metrics,
            pubmed_total_count,
            source_api_counts,
            deep_source_errors,
        ) = await _execute_deep_search(
            searcher,
            enhanced_query,
            request.limit,
            plan.effective_min_year,
            plan.effective_max_year,
            request.advanced_filters,
            strategies=plan.deep_strategies,
            search_functions=search_functions,
        )
        for error in deep_source_errors:
            logger.warning("Deep search source warning: %s", format_source_adapter_error(error))
            source_errors.append(_source_error_payload(error))
        for source, (returned, _total) in source_api_counts.items():
            attempts = [strategy for strategy in deep_search_metrics.strategy_results if strategy.source == source]
            executed_attempts = [attempt for attempt in attempts if attempt.status != "skipped_budget"]
            attempt_statuses = {attempt.status for attempt in executed_attempts}
            has_failure = "error" in attempt_statuses
            has_response = bool(attempt_statuses & {"ok", "empty", "partial"})
            if has_failure and has_response:
                source_statuses[source] = "partial"
            elif has_failure:
                source_statuses[source] = "error"
            elif "partial" in attempt_statuses:
                source_statuses[source] = "partial"
            else:
                source_statuses[source] = "ok" if returned else "empty"

            physical_queries = list(
                dict.fromkeys(
                    attempt.physical_query
                    for attempt in executed_attempts
                    if isinstance(attempt.physical_query, str) and attempt.physical_query
                )
            )
            logical_queries = list(dict.fromkeys(attempt.query for attempt in executed_attempts if attempt.query))
            warning_values: list[str] = []
            for attempt in attempts:
                attempt_warnings = attempt.metadata.get("warnings")
                if isinstance(attempt_warnings, list):
                    warning_values.extend(str(warning) for warning in attempt_warnings)
            warnings = list(dict.fromkeys(warning_values))
            source_metadata[source] = {
                "requested_mode": request.retrieval_mode,
                "provider_mode": "deep_strategy",
                "logical_query": plan.query if source == "pubmed" else plan.provider_neutral_query,
                "logical_queries": logical_queries,
                "physical_query": physical_queries[0] if len(physical_queries) == 1 else None,
                "physical_queries": physical_queries,
                "query_executed": any(attempt.query_executed for attempt in executed_attempts),
                "warnings": warnings,
                "budget": {
                    "per_source_limit": request.limit,
                    "allocated": sum(attempt.allocated_limit for attempt in attempts),
                    "returned": returned,
                },
                "attempts": [
                    {
                        "strategy": attempt.strategy_name,
                        "status": attempt.status,
                        "logical_query": attempt.query,
                        "physical_query": attempt.physical_query,
                        "query_executed": attempt.query_executed,
                        "allocated_limit": attempt.allocated_limit,
                        "returned": attempt.articles_count,
                        "total_available": attempt.total_available,
                        "metadata": dict(attempt.metadata),
                    }
                    for attempt in attempts
                ],
            }
        logger.info(
            "Deep search: %s strategies, %s with results, depth score: %.0f",
            deep_search_metrics.strategies_executed,
            deep_search_metrics.strategies_with_results,
            deep_search_metrics.depth_score,
        )
    else:
        logger.info("Using traditional source-based search (no deep search)")
        search_sources = [source for source in plan.dispatch_sources if source != "crossref"]

        def _build_search_call(source: str) -> SourceAdapterCall[UnifiedArticle]:
            async def _execute() -> SourceAdapterResult[UnifiedArticle]:
                return await _search_single_source(source, plan, search_functions)

            return SourceAdapterCall(source=source, operation="search", execute=_execute)

        search_results = await gather_source_adapter_calls(
            [_build_search_call(source) for source in search_sources],
            per_call_timeout=SOURCE_SEARCH_TIMEOUT_SECONDS,
        )

        # A default simple/lookup search often has one fast primary leg. If
        # that leg failed (rather than returning a valid empty set), make one
        # bounded provider-neutral attempt so a transient provider outage does
        # not become a false "no literature" answer. Explicit source choices
        # and provider-native/systematic contracts remain fail-closed.
        if (
            request.sources is None
            and request.retrieval_mode == "auto"
            and (analysis.complexity.value == "simple" or analysis.intent.value == "lookup")
            and search_results
            and all(result.status == "error" for result in search_results)
        ):
            from pubmed_search.infrastructure.sources.registry import get_source_registry

            registry = get_source_registry()
            fallback_source = next(
                (
                    source
                    for source in ("europe_pmc", "openalex")
                    if source not in search_sources and source in search_functions and registry.is_enabled(source)
                ),
                None,
            )
            if fallback_source is not None:
                initial_failed_sources = [result.source for result in search_results]

                async def _execute_fallback() -> SourceAdapterResult[UnifiedArticle]:
                    return await _search_single_source(
                        fallback_source,
                        plan,
                        search_functions,
                        limit_override=min(request.limit, 20),
                    )

                fallback_call: SourceAdapterCall[UnifiedArticle] = SourceAdapterCall(
                    source=fallback_source,
                    operation="fallback_search",
                    execute=_execute_fallback,
                )
                fallback_results: list[SourceAdapterResult[UnifiedArticle]] = await gather_source_adapter_calls(
                    [fallback_call],
                    per_call_timeout=SOURCE_SEARCH_TIMEOUT_SECONDS,
                )
                fallback_result = fallback_results[0]
                fallback_result.metadata.update(
                    {
                        "fallback": True,
                        "fallback_reason": "all_auto_primary_sources_failed",
                        "fallback_from": initial_failed_sources,
                        "fallback_limit": min(request.limit, 20),
                    }
                )
                search_results.append(fallback_result)

        for result in search_results:
            attempt_metadata = dict(result.metadata)
            logical_query = plan.query if result.source == "pubmed" else plan.provider_neutral_query
            attempt_metadata.setdefault("logical_query", logical_query)
            if result.source == "semantic_scholar" and request.retrieval_mode == "systematic":
                from pubmed_search.infrastructure.sources.semantic_scholar import (
                    compile_semantic_scholar_bulk_query,
                )

                try:
                    attempt_metadata.setdefault(
                        "physical_query",
                        compile_semantic_scholar_bulk_query(logical_query),
                    )
                    attempt_metadata.setdefault("query_executed", True)
                except ValueError as exc:
                    attempt_metadata.setdefault("query_compilation_error", str(exc))
                    attempt_metadata.setdefault("physical_query", None)
                    attempt_metadata.setdefault("query_executed", False)
                attempt_metadata.setdefault("provider_mode", "bulk")
            else:
                attempt_metadata.setdefault("physical_query", logical_query)
                attempt_metadata.setdefault("query_executed", True)
                attempt_metadata.setdefault("provider_mode", request.retrieval_mode)
            attempt_metadata.setdefault("requested_mode", request.retrieval_mode)
            if result.source != "pubmed" and request.advanced_filters:
                warnings = attempt_metadata.setdefault("warnings", [])
                warning = (
                    f"{result.source} does not apply PubMed-only filter(s): "
                    f"{', '.join(sorted(request.advanced_filters))}"
                )
                if isinstance(warnings, list) and warning not in warnings:
                    warnings.append(warning)

            for error in result.errors:
                log_method = logger.warning if error.retryable else logger.error
                log_method("Search source warning: %s", format_source_adapter_error(error))
                source_errors.append(_source_error_payload(error))

            articles = result.items
            raw_total_count = result.metadata.get("total_available")
            total_count = raw_total_count if isinstance(raw_total_count, int) else None
            if articles:
                all_results.append(articles)
            source_api_counts[result.source] = (len(articles), total_count)
            source_statuses[result.source] = result.status
            source_metadata[result.source] = attempt_metadata
            if result.source == "pubmed" and total_count is not None:
                pubmed_total_count = total_count
            logger.info(
                "%s: %s results%s", result.source, len(articles), f" (total: {total_count})" if total_count else ""
            )

    # Preprints (arXiv/medRxiv/bioRxiv) are first-class sources injected into
    # dispatch_sources by unified_planning when include_preprints=True. They
    # flow through the main aggregator and get deduped against published
    # versions via DOI/title matching.

    await progress(5, 10, "Aggregating results...")
    aggregator = ResultAggregator(plan.ranking_config)
    articles, stats = aggregator.aggregate(all_results)
    logger.info("Aggregation: %s unique from %s total", stats.unique_articles, stats.total_input)

    if (
        request.auto_relax
        and stats.unique_articles == 0
        and not analysis.identifiers
        and "pubmed" in plan.dispatch_sources
        and source_statuses.get("pubmed") == "empty"
    ):
        logger.info("0 results — attempting auto-relaxation")
        relaxation_result = await _auto_relax_search(
            searcher,
            plan.query,
            request.limit,
            request.min_year or analysis.year_from,
            request.max_year or analysis.year_to,
            request.advanced_filters,
        )
        if relaxation_result and relaxation_result.successful_step:
            step = relaxation_result.successful_step
            all_results = [relaxation_result.articles]
            articles, stats = aggregator.aggregate(all_results)
            pubmed_total_count = relaxation_result.total_results
            source_api_counts["pubmed"] = (
                len(relaxation_result.articles),
                relaxation_result.total_results,
            )
            source_statuses["pubmed"] = "ok"
            source_metadata["pubmed"] = {
                "total_available": relaxation_result.total_results,
                "requested_mode": request.retrieval_mode,
                "provider_mode": "auto_relax",
                "original_query": relaxation_result.original_query,
                "canonical_query": relaxation_result.relaxed_query,
                "relaxation_level": step.level,
                "relaxation_action": step.action,
                "replaces_empty_federation": True,
            }
            logger.info("Auto-relaxation: %s results at level %s (%s)", stats.unique_articles, step.level, step.action)

    await progress(6, 10, "Enriching results...")
    enrichment_tasks: list[asyncio.Task] = []  # type: ignore[type-arg]
    if "crossref" in plan.dispatch_sources:
        enrichment_tasks.append(asyncio.create_task(_enrich_with_crossref(articles)))
    if "openalex" in plan.dispatch_sources:
        enrichment_tasks.append(asyncio.create_task(_enrich_with_journal_metrics(articles)))
    if request.include_oa_links and DispatchStrategy.should_enrich_with_unpaywall(analysis):
        enrichment_tasks.append(asyncio.create_task(_enrich_with_unpaywall(articles)))
    if enrichment_tasks:
        await asyncio.gather(*enrichment_tasks, return_exceptions=True)

    if (
        request.peer_reviewed_only
        and articles
        and not _allows_preprint_articles(
            include_preprints=request.include_preprints,
            dispatch_sources=plan.dispatch_sources,
        )
    ):
        from pubmed_search.domain.entities.article import ArticleType

        pre_filter_count = len(articles)
        articles = [article for article in articles if not _is_preprint(article, ArticleType)]
        filtered_count = pre_filter_count - len(articles)
        if filtered_count > 0:
            logger.info("Peer-review filter: removed %s non-peer-reviewed articles", filtered_count)

    await progress(8, 10, "Ranking results...")
    ranked = aggregator.rank(articles, plan.ranking_config, plan.query)
    if request.limit and len(ranked) > request.limit:
        ranked = ranked[: request.limit]

    if request.include_similarity_scores:
        _enrich_with_similarity_scores(ranked, plan.query)

    source_disagreement = None
    if request.show_analysis and len(source_api_counts) > 1:
        from pubmed_search.application.search.ranking_algorithms import analyze_source_disagreement

        source_disagreement = analyze_source_disagreement(ranked)

    reproducibility = None
    if request.show_analysis:
        from pubmed_search.application.search.reproducibility import calculate_reproducibility

        sources_queried_list = (
            list(source_api_counts.keys())
            if source_api_counts
            else [source for source in plan.dispatch_sources if source != "crossref"]
        )
        sources_responded_list = (
            [
                source
                for source in sources_queried_list
                if source_statuses.get(source, "empty") in {"ok", "empty", "partial"}
            ]
            if source_api_counts
            else sources_queried_list
        )
        reproducibility = calculate_reproducibility(
            query=plan.query,
            sources_queried=sources_queried_list,
            sources_responded=sources_responded_list,
            articles=ranked,
            has_source_counts=bool(source_api_counts),
        )

    research_context_preview: str | None = None
    research_context_data: dict[str, Any] | None = None
    if request.include_research_context and ranked:
        pmids_for_context = [str(article.pmid) for article in ranked if getattr(article, "pmid", None)][:20]
        if pmids_for_context:
            try:
                context_builder = timeline_builder_cls(searcher)
                context_timeline = await context_builder.build_timeline_from_pmids(
                    pmids=pmids_for_context, topic=analysis.original_query
                )
                if context_timeline.events:
                    context_tree = research_tree_builder(context_timeline)
                    research_context_preview = context_tree.to_text_tree()
                    research_context_data = context_tree.to_dict()
            except Exception as exc:
                logger.debug("Research context graph skipped (%s)", type(exc).__name__)

    prefetched_trials: list[Any] | None = None
    if clinical_trials_task:
        try:
            prefetched_trials = await asyncio.wait_for(
                clinical_trials_task,
                timeout=CLINICAL_TRIALS_PREFETCH_TIMEOUT_SECONDS,
            )
            clinical_trials_status = "ok" if prefetched_trials else "empty"
        except asyncio.TimeoutError:
            clinical_trials_status = "timeout"
            logger.debug(
                "Clinical trials prefetch exceeded %.2fs budget",
                CLINICAL_TRIALS_PREFETCH_TIMEOUT_SECONDS,
            )
        except Exception:
            prefetched_trials = None
            clinical_trials_status = "error"

    return UnifiedSearchExecutionResult(
        ranked=ranked,
        stats=stats,
        pubmed_total_count=pubmed_total_count,
        source_api_counts=source_api_counts,
        deep_search_metrics=deep_search_metrics,
        relaxation_result=relaxation_result,
        source_disagreement=source_disagreement,
        reproducibility_score=reproducibility,
        research_context_preview=research_context_preview,
        research_context_data=research_context_data,
        prefetched_trials=prefetched_trials,
        clinical_trials_query=clinical_trials_query,
        clinical_trials_status=clinical_trials_status,
        source_errors=source_errors,
        source_statuses=source_statuses,
        source_metadata=source_metadata,
    )


__all__ = ["UnifiedSearchExecutionResult", "execute_unified_search"]
